package com.alex22sv.coffeeapp.Classes;

public enum AuditLogAction {
    LOGGED_IN,
    LOGGED_OUT,
    ADDED_CONSUMED_COFFEE,
    FAILED_TO_ADD_CONSUMED_COFFEE,
    UPDATED_CONSUMED_COFFEE,
    FAILED_TO_UPDATE_CONSUMED_COFFEE,
    DELETED_CONSUMED_COFFEE,
    FAILED_TO_DELETE_CONSUMED_COFFEE,
    ADDED_COFFEE_BRAND,
    FAILED_TO_ADD_COFFEE_BRAND,
    UPDATED_COFFEE_BRAND,
    FAILED_TO_UPDATE_COFFEE_BRAND,
    DELETED_COFFEE_BRAND,
    FAILED_TO_DELETE_COFFEE_BRAND
}
